name = "api"
type = "javascript"
zone_id = ""
account_id = ""
route = "lablackmarket.spookelton.net/*"

compatibility_date = "2022-06-05"

kv_namespaces = [
         { binding = "listings", id = "" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
dir = "./build"
main = "./index.mjs"